# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Age of a Dragon
email: hallkd47@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My gamedev blog for updates on developing my first major game project, 'Age of a Dragon.' 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kyle-hall.github.io/age-of-a-dragon" # the base hostname & protocol for your site
twitter_username: kylohall
github_username:  kyle-hall

# Build settings
markdown: kramdown
